### ISSUE TITLE
RTL pagination support ❓ 

### ISSUE THREAD

**Issue by firemanx07** [dozsolti/react-native-use-list#1]
does the pagination here support RTL ? it would be awesome if it does .

**Comment by dozsolti** [comment]
Thank you for the question, It does support RTL by default.

All you need to do is add the `inverted` prop to the `FlatList` and swap up to pagination buttons. 
Call `prevPage()` when you want to move the list to the _right_ and call `nextPage()` for when you want to move it to the _left_.
Example:

        <Button text="<" onPress={nextPage} />
        <Text>{pageIndex}</Text>
        <Button text=">" onPress={prevPage} />
        
The `pageIndex` will be updated when you put the inverted prop, making the far rightest element index 0.

**Comment by firemanx07** [comment]
@dozsolti well in use-case to support both LTR and RTL depending on user language preferences 
`nextPage( ) `and` previousPage( )` didn't go well (ios most of the case) . 
my work around 2-way indexing of the list of ` data =[isRTL ?data:invertedData`] 
and use `goToPage(index)`

**Comment by dozsolti** [comment]
@firemanx07 It works out of the box. 

👉 All you need to do is add `inverted={isRTL}` to your FlatList.

And everything will be flipped: your data, the page index, and the buttons.
You can use the nextPage and prevPage as if they were LTR
